server:
  port: 7100
spring:
  application:
    name: xxl-job-demo

xxl:
  job:
    admin:
      addresses: http://192.168.1.215:8080/xxl-job-admin
    executor:
      appname: xxl-job-demo
      logpath: C:/mao/intellijIde/xxl-job/data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999
      address: http://192.168.1.215:8080/xxl-job-admin
      ip:
    accessToken:
